export const isParceledOptions = [
  {
    label: 'Sim',
    value: true
  },
  {
    label: 'Não',
    value: false
  }
];

export const paymentOptions = [
  {
    label: '643 -	CAIXA',
    value: '643 -	CAIXA'
  },
  {
    label: '645 - CAIXA',
    value: '645 - CAIXA'
  },
  {
    label: '644 - BANCOS CONTA MOVIMENTO',
    value: '644 - BANCOS CONTA MOVIMENTO'
  },
  {
    label: '5 - BRADESCO C/C',
    value: '5 - BRADESCO C/C'
  },
  {
    label: '6 - BANCO DO BRASIL S/A',
    value: '6 - BANCO DO BRASIL S/A'
  },
  {
    label: '7 - CAIXA ECONÔMICA FEDERAL S/A',
    value: '7 - CAIXA ECONÔMICA FEDERAL S/A'
  },
  {
    label: '633 - SANTANDER',
    value: '633 - SANTANDER'
  },
  {
    label: '634 - BANCO ITAÚ',
    value: '634 - BANCO ITAÚ'
  },
  {
    label: '636 - BANCO HSBC',
    value: '636 - BANCO HSBC'
  },
  {
    label: '635 - BRADESCO C/P',
    value: '635 - BRADESCO C/P'
  },
  {
    label: '9 - BANCO DO BRASIL',
    value: '9 - BANCO DO BRASIL'
  },
  {
    label: '647 - SANTANDER',
    value: '647 - SANTANDER'
  },
  {
    label: '648 - CAIXA ECONÔMICA FEDERAL',
    value: '648 - CAIXA ECONÔMICA FEDERAL'
  },
  {
    label: '679 - BANCO DO BRASIL S/A',
    value: '679 - BANCO DO BRASIL S/A'
  },
  {
    label: '680 - CAIXA ECONÔMICA FEDERAL',
    value: '680 - CAIXA ECONÔMICA FEDERAL'
  },
  {
    label: '682 - BANCO ITAÚ',
    value: '682 - BANCO ITAÚ'
  },
  {
    label: '681 - SANTANDER',
    value: '681 - SANTANDER'
  },
  {
    label: '683 -	BRADESCO',
    value: '683 -	BRADESCO'
  },
  {
    label: '52 -	BANCO DO BRASIL S/A',
    value: '52 -	BANCO DO BRASIL S/A'
  },
  {
    label: '122 - CAIXA ECONÔMICA FEDERAL',
    value: '122 - CAIXA ECONÔMICA FEDERAL'
  },
  {
    label: '123 - BRADESCO',
    value: '123 - BRADESCO'
  },
  {
    label: '124 - SANTANDER',
    value: '124 - SANTANDER'
  },
  {
    label: '125 - BANCO ITAÚ',
    value: '125 - BANCO ITAÚ'
  }
];

export const typesOptions = [
  {
    label: '646 -	APLICAÇÕES DE LIQUIDEZ IMEDIATA',
    value: '646 -	APLICAÇÕES DE LIQUIDEZ IMEDIATA'
  },
  {
    label: '4 -	APLICAÇÃO AUTOMÁTICA MAIS',
    value: '4 -	APLICAÇÃO AUTOMÁTICA MAIS'
  },
  {
    label: '637 -	APLICAÇÕES FINANCEIRAS DIVERSAS',
    value: '637 -	APLICAÇÕES FINANCEIRAS DIVERSAS'
  },
  {
    label: '638 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - BRADESCO',
    value: '638 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - BRADESCO'
  },
  {
    label: '639 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - CEF',
    value: '639 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - CEF'
  },
  {
    label: '640 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - SANTANDER',
    value: '640 -	APLICAÇÃO EM CADERNETA DE POUPANÇA - SANTANDER'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '642 -	APLICAÇÃO EM TÍTULOS DE CAPITALIZAÇÃO',
    value: '642 -	APLICAÇÃO EM TÍTULOS DE CAPITALIZAÇÃO'
  },
  {
    label: '11 - DIREITOS REALIZÁVEIS A CURTO PRAZO',
    value: '11 - DIREITOS REALIZÁVEIS A CURTO PRAZO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '649 -	CONTRIBUIÇÕES A RECEBER',
    value: '649 -	CONTRIBUIÇÕES A RECEBER'
  },
  {
    label: '13 - CHEQUES A DEPOSITAR',
    value: '13 - CHEQUES A DEPOSITAR'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  },
  {
    label: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO',
    value: '641 -	APLICAÇÃO DEPÓSITO ESPECIAL REMUNERADO'
  }

  //
  //
  //
  //
  //
  //
  //
  //   14	MENSALIDADES A RECEBER
  //   12	APLICAÇÕES FINANCEIRAS DE RENDA FIXA
  //   650	APLICAÇÃO NO FUNDO DE COMODITIES
  //   651	APLICAÇÃO MAX DI
  //   652	APLICAÇÃO  SUPER DI
  //   653	APLICAÇÃO COMPROMISSADA DI
  //   654	APLICAÇÃO FINANCEIRA CDB - ITAÚ
  //   655	APLICAÇÃO ITAÚ SUPER RF
  //   656	APLICAÇÃO MAX RF
  //   657	APLICAÇÃO ITAUVEST
  //   658	APLICAÇÃO FICFI REF BRADESCO
  //   659	APLICAÇÕES FINANCEIRAS DE RENDA VARIÁVEL
  //   660	APLICAÇÃO EM AÇÕES
  //   661	APLICAÇÃO EM FUNDOS DE INVESTIMENTO
  //   662	EMPRÉSTIMOS
  //   663	EMPRÉSTIMOS CONCEDIDOS A CONTRIBUINTES
  //   664	EMPRÉSTIMOS CONCEDIDOS A TERCEIROS
  //   665	CONTRIBUIÇÕES E IMPOSTOS A RECUPERAR
  //   666	INSS A RECUPERAR
  //   667	IRRF A RECUPERAR
  //   668	PIS A RECUPERAR
  //   669	FGTS A RECUPERAR
  //   28	ADIANTAMENTOS E GRATUIDADES CONDICIONAIS
  //   25	ADIANTAMENTOS SALARIAIS
  //   26	ADIANTAMENTOS DO 13º SALÁRIO
  //   31	ADIANTAMENTO A FORNECEDORES
  //   32	ADIANTAMENTOS DE VIAGEM
  //   632	ADIANTAMENTO DE FERIAS
  //   35	DESPESAS DO EXERCÍCIO SEGUINTE
  //   36	ASSINATURAS DE PERIÓDICOS
  //   37	SEGUROS A APROPRIAR
  //   670	IPTU A APROPRIAR
  //   671	IPVA A APROPRIAR
  //   585	ATIVO NÃO CIRCULANTE
  //   39	REALIZÁVEL A LONGO PRAZO
  //   40	APLICAÇÕES FINANCEIRAS
  //   672	CONTAS A RECEBER
  //   673	CONTAS A RECEBER FILIAIS
  //   42	DEPÓSITOS JUDICIAIS
  //   43	DEPÓSITOS PARA GARANTIA DE INSTÂNCIAS
  //   44	INVESTIMENTOS
  //   45	AÇÕES DE RENDA
  //   46	IMÓVEIS LOCADOS
  //   47	IMOBILIZADO
  //   113	TERRENOS
  //   114	EDIFICAÇÕES
  //   115	CONSTRUÇÕES EM ANDAMENTO
  //   51	INSTALAÇÕES
  //   121	VEÍCULOS
  //   117	MÓVEIS E UTENSÍLIOS
  //   54	EQUIPAMENTOS DE COMUNICAÇÃO E INFORMÁTICA
  //   119	MÁQUINAS E EQUIPAMENTOS
  //   589	BENFEITORIAS EM IMÓVEIS DE TERCEIROS
  //   674	FERRAMENTAS
  //   675	INSTRUMENTOS MUSICAIS
  //   676	COMPUTADORES E PERIFÉRICOS
  //   677	IMÓVEIS
  //   771	DEPRECIAÇÃO ACUMULADA
  //   772	(-) EDIFICAÇÕES - DEPRECIAÇÃO
  //   773	(-) INSTALAÇÕES - DEPRECIAÇÃO
  //   774	(-) VEÍCULOS - DEPRECIAÇÃO
  //   775	(-) MÓVEIS E UTENSÍLIOS - DEPRECIAÇÃO
  //   776	(-) EQUIPAMENTOS DE COMUNICAÇÃO E INFORMÁTICA - DEPRECIAÇÃO
  //   777	(-) MÁQUINAS E EQUIPAMENTOS - DEPRECIAÇÃO
  //   778	(-) FERRAMENTAS - DEPRECIAÇÃO
  //   779	(-) COMPUTADORES E PERIFÉRICOS - DEPRECIAÇÃO
  //   780	(-) IMÓVEIS - DEPRECIAÇÃO
  //   58	INTANGÍVEL
  //   59	MARCAS E PATENTES
  //   758	CAPITAL INTELECTUAL
  //   759	FUNDOS DE COMÉRCIO
  //   760	DIREITOS AUTORAIS
  //   761	CONCESSÕES
  //   762	SOFTWARES OU PROGRAMAS DE COMPUTADOR
  //   763	FRANQUIAS
  //   60	(-) AMORTIZAÇÃO ACUMULADA
  //   764	(-) CAPITAL INTELECTUAL - AMORTIZAÇÃO
  //   765	(-) MARCAS E PATENTES - AMORTIZAÇÃO
  //   766	(-) FUNDOS DE COMÉRCIO - AMORTIZAÇÃO
  //   767	(-) CONCESSÕES - AMORTIZAÇÕES
  //   768	(-) DIREITOS AUTORAIS - AMORTIZAÇÃO
  //   769	(-) SOFTWARES - AMORTIZAÇÃO
  //   770	(-) FRANQUIAS - AMORTIZAÇÃO
  //   61	PASSIVO
  //   62	CIRCULANTE
  //   63	OBRIGAÇÕES COM INSTITUIÇÕES DE CRÉDITO
  //   678	EMPRÉSTIMOS E FINANCIAMENTOS BANCÁRIOS
  // 684	EMPRÉSTIMOS E FINANCIAMENTOS DIVERSOS
  // 685	EMPRÉSTIMOS OBTIDOS
  // 686	FINANCIAMENTOS
  // 69	VINCULADO AO FORNECIMENTO DE MATERIAL E SERVIÇOS
  // 506	FORNECEDORES
  // 71	FRETES A PAGAR
  // 72	CONTAS A PAGAR
  // 693	SEGUROS A PAGAR
  // 80	VINCULADO A OBRIGAÇÕES TRIBUTÁRIAS E SOCIAIS
  // 192	FGTS Á RECOLHER
  // 191	INSS A RECOLHER
  // 575	IRRF Á RECOLHER
  // 494	PIS SOBRE FOLHA A RECOLHER
  // 553	CONTRIBUIÇÃO ASSISTENCIAL A RECOLHER
  // 178	IRRF SOBRE FOLHA Á RECOLHER
  // 491	SINDICAL A RECOLHER
  // 528	PENSÃO ALIMENTÍCIA A DEPOSITAR
  // 688	INSS MINISTERIAL A PAGAR
  // 689	ISS A RECOLHER
  // 690	IPTU A RECOLHER
  // 691	IPVA A RECOLHER
  // 692	CSLL/PIS/COFINS A RECOLHER
  // 88	OBRIGAÇÕES COM EMPREGADOS
  // 187	SALÁRIOS A PAGAR
  // 194	FÉRIAS A PAGAR
  // 512	RESCISÕES Á PAGAR
  // 517	13º A PAGAR
  // 584	ESTAGIARIOS A PAGAR
  // 525	AUTONOMOS Á PAGAR
  // 694	SUSTENTO MINISTERIAL A PAGAR
  // 738	PROVISÕES
  // 739	PROVISÃO DE 13º SALÁRIO
  // 740	PROVISÃO DE 13º SALÁRIO
  // 741	PROVISÃO DE INSS SOBRE 13º SALPARIO
  // 742	PROVISÃO DE FGTS SOBRE 13º SALÁRIO
  // 755	PROVISÃO DE PIS SOBRE 13º SALÁRIO
  // 743	PROVISÃO DE FÉRIAS
  // 744	PROVISÃO DE FÉRIAS
  // 745	PROVISÃO DE INSS SOBRE FÉRIAS
  // 746	PROVISÃO DE FGTS SOBRE FÉRIAS
  // 756	PROVISÃO DE PIS SOBRE FÉRIAS
  // 747	REPASSES
  // 748	JUNTA DE MISSÕES NACIONAIS
  // 749	JUNTA DE MISSÕES ESTADUAIS
  // 750	JUNTA DE MISSÕES MUNDIAIS
  // 751	CONVENÇÃO BATISTA FLUMINENSE
  // 752	PLANO COOPERATIVO
  // 753	LAR BATISTA
  // 754	REVISTAS
  // 29	PASSIVO NÃO CIRCULANTE
  // 120	OBRIGAÇÕES COM INSTITUIÇÕES DE CRÉDITO
  // 757	EMPRÉSTMOS E FINANCIAMENTOS
];
